# NOTE: This file is not a stand-alone package. It is part of
# a 'root' device template and expects the substitutions that
# are hereby referenced to be defined by its parent.

light:
  # Physical pin to the connection status LED
  # We don't expose this to the HA UI (internal)
  - platform: status_led
    name: "LED"
    id: led_status
    pin:
      number: GPIO05
      inverted: true
      ignore_strapping_warning: true
    internal: false
    restore_mode: RESTORE_DEFAULT_ON

binary_sensor:

  # Make the status LED blink when not connected/trying to connect
  - platform: template
    name: "API connected"
    id: sensor_api_connected
    internal: true
    entity_category: 'diagnostic'
    device_class: 'connectivity'
    lambda: return global_api_server->is_connected();
    on_press:
      - if:
          condition:
            switch.is_on: den_bao_ket_noi_api_switch
          then:
            - light.turn_off: led_status
    on_release:
      - if:
          condition:
            switch.is_on: den_bao_ket_noi_api_switch
          then:
            - light.turn_on: led_status
